[enb]
enb_id = 0x022
mcc = 999
mnc = 70
mme_addr = 10.10.1.1
gtp_bind_addr = 10.10.1.132
s1c_bind_addr = 10.10.1.132
s1c_bind_port = 0
n_prb = 50

[enb_files]
sib_config = /etc/srsenb/sib.conf
rr_config  = /etc/srsenb/rr.conf
rb_config  = /etc/srsenb/rb.conf

[rf]
dl_earfcn = 3350
tx_gain   = 80
rx_gain   = 40
device_name = zmq
device_args = fail_on_disconnect=true,tx_port=tcp://*:40340,rx_port=tcp://10.10.1.4:40341,id=enb34,base_srate=11.52e6

[expert]
rrc_inactivity_timer = 1073741823
metrics_csv_enable   = true
metrics_csv_filename = /tmp/gnb1_ue34_metrics.csv
metrics_period_secs  = 1

[log]
all_level    = info
filename     = /tmp/gnb1_logs/ue34.log
file_max_size = -1

[pcap]
enable = false
