mac_cnfg =
{
  phr_cnfg =
  {
    dl_pathloss_change = "dB3";
    periodic_phr_timer = 50;
    prohibit_phr_timer = 0;
  };
  ulsch_cnfg =
  {
    max_harq_tx        = 4;
    periodic_bsr_timer = 20;
    retx_bsr_timer     = 320;
  };
  time_alignment_timer = -1;
};

phy_cnfg =
{
  phich_cnfg =
  {
    duration  = "Normal";
    resources = "1/6";
  };
  pusch_cnfg_ded =
  {
    beta_offset_ack_idx = 6;
    beta_offset_ri_idx  = 6;
    beta_offset_cqi_idx = 6;
  };
  sched_request_cnfg =
  {
    dsr_trans_max = 64;
    period        = 20;
    nof_prb       = 1;
  };
  cqi_report_cnfg =
  {
    mode              = "periodic";
    simultaneousAckCQI = true;
    period            = 40;
    m_ri              = 8;
  };
};

cell_list =
(
  {
    cell_id    = 0x01;
    tac        = 0x0001;
    pci        = 1;
    dl_earfcn  = 3350;
    ho_active  = false;
    scell_list = ();
    meas_cell_list = ();
    meas_report_desc = ();
    meas_quant_desc = { rsrq_config = 4; rsrp_config = 4; };
  }
);

nr_cell_list = ();
