[rf]
freq_offset  = 0
tx_gain      = 80
rx_gain      = 40
nof_antennas = 1
device_name  = zmq
device_args  = fail_on_disconnect=true,tx_port=tcp://*:40821,rx_port=tcp://10.10.1.2:40820,id=ue82,base_srate=11.52e6

[rat.eutra]
dl_earfcn    = 3350
nof_carriers = 1

[usim]
mode = soft
algo = milenage
opc  = 63bfa50ee6523365ff14c1f45f88737d
k    = 00112233445566778899aabbccddeeff
imsi = 999700000000082
imei = 353490060000082

[rrc]
release     = 8
ue_category = 4

[nas]
apn          = internet
apn_protocol = ipv4

[gw]
netns      = ue82
ip_devname = tun_srsue82
ip_netmask = 255.255.255.0

[log]
all_level    = info
filename     = /tmp/ue82.log
file_max_size = -1
